// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIC.EntityFrameworkCore;

namespace SMIC.Migrations.SDIMDb
{
    [DbContext(typeof(SDIMDbContext))]
    [Migration("20191203083706_add_VW_SJCL_100")]
    partial class add_VW_SJCL_100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SMIC.SDIM.JBCS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Axles");

                    b.Property<double>("BCFW");

                    b.Property<double>("BCJDA");

                    b.Property<double>("BCJDB");

                    b.Property<double>("CJJD");

                    b.HasKey("Id");

                    b.ToTable("JBCSS");
                });

            modelBuilder.Entity("SMIC.SDIM.JDRQ", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("jdrq");

                    b.Property<int>("jdzt");

                    b.Property<DateTime>("jwrq");

                    b.HasKey("Id");

                    b.ToTable("JDRQS");
                });

            modelBuilder.Entity("SMIC.SDIM.RecentSJMX", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("仪器件数");

                    b.Property<string>("委托单号");

                    b.Property<string>("检定状态");

                    b.Property<string>("送检单位");

                    b.Property<string>("送检日期");

                    b.HasKey("Id");

                    b.ToTable("RecentSJMX");
                });

            modelBuilder.Entity("SMIC.SDIM.SJMX", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bzsm");

                    b.Property<string>("ccbh");

                    b.Property<DateTime>("djrq");

                    b.Property<DateTime>("jdrq");

                    b.Property<string>("jdy");

                    b.Property<string>("jdzt1");

                    b.Property<string>("jdzt2");

                    b.Property<DateTime>("jwrq");

                    b.Property<string>("qjmc");

                    b.Property<string>("sjdid");

                    b.Property<string>("wtdh");

                    b.Property<string>("wtdw");

                    b.Property<string>("xhggbm");

                    b.Property<string>("xhggmc");

                    b.Property<DateTime>("yqjcrq");

                    b.Property<string>("zzc");

                    b.HasKey("Id");

                    b.ToTable("SJMX");
                });

            modelBuilder.Entity("SMIC.SDIM.STATS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bm");

                    b.Property<int>("count");

                    b.Property<int>("m");

                    b.Property<int>("y");

                    b.HasKey("Id");

                    b.ToTable("STATS");
                });

            modelBuilder.Entity("SMIC.SDIM.VW_SJMX", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("出厂编号");

                    b.Property<string>("单位名称");

                    b.Property<string>("器具名称");

                    b.Property<string>("型号规格");

                    b.Property<string>("检定状态");

                    b.Property<string>("证书编号");

                    b.Property<double>("送检单ID");

                    b.Property<string>("送检单号");

                    b.Property<DateTime>("送检日期");

                    b.HasKey("Id");

                    b.ToTable("VW_SJMX");
                });

            modelBuilder.Entity("SMIC.SDIM.WTD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dwmc");

                    b.Property<string>("jdzt");

                    //b.Property<string>("q zyjdzt");

                    //b.Property<int>("q zyjs");

                    b.Property<string>("sjdid");

                    b.Property<DateTime>("sjrq");

                    b.Property<DateTime>("yqjcrq");

                    b.Property<int>("yqjs");

                    b.HasKey("Id");

                    b.ToTable("WTD");
                });
#pragma warning restore 612, 618
        }
    }
}
